var setup = [
  [
    {"color": "w", "name": "queen", "symbol": "R"},
    {"color": "w", "name": "queen", "symbol": ""},
    {},
    {},
    {},
    {},
    {"color": "b", "name": "queen", "symbol": ""},
    {"color": "b", "name": "queen", "symbol": "R"},
  ],
  [
    {"color": "w", "name": "queen", "symbol": "N"},
    {"color": "w", "name": "queen", "symbol": ""},
    {},
    {},
    {},
    {},
    {"color": "b", "name": "queen", "symbol": ""},
    {"color": "b", "name": "queen", "symbol": "N"},
  ],
  [
    {"color": "w", "name": "queen", "symbol": "B"},
    {"color": "w", "name": "queen", "symbol": ""},
    {},
    {},
    {},
    {},
    {"color": "b", "name": "queen", "symbol": ""},
    {"color": "b", "name": "queen", "symbol": "B"},
  ],
  [
    {"color": "w", "name": "queen", "symbol": "Q"},
    {"color": "w", "name": "queen", "symbol": ""},
    {},
    {},
    {},
    {},
    {"color": "b", "name": "queen", "symbol": ""},
    {"color": "b", "name": "queen", "symbol": "Q"},
  ],
  [
    {"color": "w", "name": "king", "symbol": "K"},
    {"color": "w", "name": "queen", "symbol": ""},
    {},
    {},
    {},
    {},
    {"color": "b", "name": "queen", "symbol": ""},
    {"color": "b", "name": "king", "symbol": "K"},
  ],
  [
    {"color": "w", "name": "queen", "symbol": "B"},
    {"color": "w", "name": "queen", "symbol": ""},
    {},
    {},
    {},
    {},
    {"color": "b", "name": "queen", "symbol": ""},
    {"color": "b", "name": "queen", "symbol": "B"},
  ],
  [
    {"color": "w", "name": "queen", "symbol": "N"},
    {"color": "w", "name": "queen", "symbol": ""},
    {},
    {},
    {},
    {},
    {"color": "b", "name": "queen", "symbol": ""},
    {"color": "b", "name": "queen", "symbol": "N"},
  ],
  [
    {"color": "w", "name": "queen", "symbol": "R"},
    {"color": "w", "name": "queen", "symbol": ""},
    {},
    {},
    {},
    {},
    {"color": "b", "name": "queen", "symbol": ""},
    {"color": "b", "name": "queen", "symbol": "R"},
  ]
];
