/** Setup for standard chess: https://www.chess.com/article/view/how-to-set-up-a-chessboard */
var setup = [
  [
    {"color": "w", "name": "rook", "symbol": "R"},
    {"color": "w", "name": "pawn", "symbol": ""},
    {},
    {},
    {},
    {},
    {"color": "b", "name": "pawn", "symbol": ""},
    {"color": "b", "name": "rook", "symbol": "R"},
  ],
  [
    {"color": "w", "name": "knight", "symbol": "N"},
    {"color": "w", "name": "pawn", "symbol": ""},
    {},
    {},
    {},
    {},
    {"color": "b", "name": "pawn", "symbol": ""},
    {"color": "b", "name": "knight", "symbol": "N"},
  ],
  [
    {"color": "w", "name": "bishop", "symbol": "B"},
    {"color": "w", "name": "pawn", "symbol": ""},
    {},
    {},
    {},
    {},
    {"color": "b", "name": "pawn", "symbol": ""},
    {"color": "b", "name": "bishop", "symbol": "B"},
  ],
  [
    {"color": "w", "name": "queen", "symbol": "Q"},
    {"color": "w", "name": "pawn", "symbol": ""},
    {},
    {},
    {},
    {},
    {"color": "b", "name": "pawn", "symbol": ""},
    {"color": "b", "name": "queen", "symbol": "Q"},
  ],
  [
    {"color": "w", "name": "king", "symbol": "K"},
    {"color": "w", "name": "pawn", "symbol": ""},
    {},
    {},
    {},
    {},
    {"color": "b", "name": "pawn", "symbol": ""},
    {"color": "b", "name": "king", "symbol": "K"},
  ],
  [
    {"color": "w", "name": "bishop", "symbol": "B"},
    {"color": "w", "name": "pawn", "symbol": ""},
    {},
    {},
    {},
    {},
    {"color": "b", "name": "pawn", "symbol": ""},
    {"color": "b", "name": "bishop", "symbol": "B"},
  ],
  [
    {"color": "w", "name": "knight", "symbol": "N"},
    {"color": "w", "name": "pawn", "symbol": ""},
    {},
    {},
    {},
    {},
    {"color": "b", "name": "pawn", "symbol": ""},
    {"color": "b", "name": "knight", "symbol": "N"},
  ],
  [
    {"color": "w", "name": "rook", "symbol": "R"},
    {"color": "w", "name": "pawn", "symbol": ""},
    {},
    {},
    {},
    {},
    {"color": "b", "name": "pawn", "symbol": ""},
    {"color": "b", "name": "rook", "symbol": "R"},
  ]
];
